# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Ajaya's Rambling 
tagline:          openstack 
paginate:         1
baseurl:          /
author:
  name:           Mark Otto
  url:            https://twitter.com/aj_agr

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/ajayaa.github.io

pages_list:       
  About: '/about/'
  Archive: '/archive/'
